from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a weighted topology+FHS hybrid from an existing forecasts.csv, "
            "tune weight on validation, and evaluate on test."
        )
    )
    parser.add_argument(
        "--forecasts",
        type=Path,
        default=Path("results/topology_pipeline/forecasts.csv"),
        help="Path to forecasts.csv generated by the topology pipeline.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/topology_fhs_hybrid"),
        help="Directory for hybrid outputs.",
    )
    parser.add_argument(
        "--weights",
        type=str,
        default="0,0.05,0.1,0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.95,1.0",
        help="Comma-separated topology weights to scan (0..1).",
    )
    parser.add_argument(
        "--topology-method",
        type=str,
        default="topology_knn",
        help="Topology method name in forecasts.csv.",
    )
    parser.add_argument(
        "--fhs-method",
        type=str,
        default="fhs_ewma",
        help="FHS method name in forecasts.csv.",
    )
    parser.add_argument(
        "--selection-objective",
        type=str,
        choices=("fz", "coverage_then_fz", "weighted_combo"),
        default="fz",
        help=(
            "Validation objective for selecting topology weight: "
            "'fz' minimizes mean FZ-style score, "
            "'coverage_then_fz' prioritizes VaR exceedance proximity to target then FZ, "
            "'weighted_combo' minimizes weighted sum of both."
        ),
    )
    parser.add_argument(
        "--target-var-exceedance",
        type=float,
        default=0.01,
        help="Target VaR exceedance rate used by non-fz objectives.",
    )
    parser.add_argument(
        "--coverage-weight",
        type=float,
        default=0.7,
        help="Coverage weight for 'weighted_combo' objective (0..1).",
    )
    return parser.parse_args()


def _parse_weight_grid(weight_text: str) -> list[float]:
    weights = [float(x.strip()) for x in weight_text.split(",") if x.strip()]
    if not weights:
        raise ValueError("Weight grid is empty.")
    for value in weights:
        if not (0.0 <= value <= 1.0):
            raise ValueError(f"Weight out of range [0,1]: {value}")
    return sorted(set(weights))


def _fz_style_score(
    losses: np.ndarray,
    var_values: np.ndarray,
    es_values: np.ndarray,
    alpha_var: float = 0.99,
    alpha_es: float = 0.975,
) -> np.ndarray:
    var_term = np.where(
        losses >= var_values,
        alpha_var * (losses - var_values),
        (1.0 - alpha_var) * (var_values - losses),
    )
    es_term = np.where(
        losses >= es_values,
        losses - es_values,
        alpha_es * (es_values - losses),
    )
    return var_term + es_term


def _summarize_frame(frame: pd.DataFrame) -> pd.DataFrame:
    return (
        frame.groupby(["split", "method"], dropna=False)
        .agg(
            n_forecasts=("realized_date", "size"),
            mean_var_99=("VaR_99", "mean"),
            mean_es_975=("ES_975", "mean"),
            exceedance_rate_99=("var_exceedance_99", "mean"),
            exceedance_rate_es_975=("es_exceedance_975", "mean"),
            mean_realized_loss=("realized_loss", "mean"),
            mean_fz_style=("fz_style_score", "mean"),
        )
        .reset_index()
        .sort_values(["split", "method"])
    )


def _variant_columns(frame: pd.DataFrame, allowed: list[str]) -> list[str]:
    cols: list[str] = []
    for col in allowed:
        if col in frame.columns and frame[col].notna().any():
            cols.append(col)
    return cols


def _select_with_variant_id(
    forecasts: pd.DataFrame,
    method_name: str,
    variant_cols: list[str],
) -> pd.DataFrame:
    subset = forecasts[forecasts["method"] == method_name].copy()
    if subset.empty:
        raise ValueError(f"Method not found in forecasts: {method_name}")
    if not variant_cols:
        subset["variant_id"] = method_name
        return subset

    as_text = subset[variant_cols].fillna("NA").astype(str)
    subset["variant_id"] = as_text.agg("|".join, axis=1)
    return subset


def _build_hybrid(aligned: pd.DataFrame, weight_topology: float) -> pd.DataFrame:
    out = pd.DataFrame(
        {
            "forecast_date": aligned["forecast_date_topo"],
            "realized_date": aligned["realized_date"],
            "split": aligned["split_topo"],
            "method": "hybrid_topology_fhs",
            "scenario_count": aligned["scenario_count_topo"] + aligned["scenario_count_fhs"],
            "VaR_99": (
                weight_topology * aligned["VaR_99_topo"]
                + (1.0 - weight_topology) * aligned["VaR_99_fhs"]
            ),
            "ES_975": (
                weight_topology * aligned["ES_975_topo"]
                + (1.0 - weight_topology) * aligned["ES_975_fhs"]
            ),
            "realized_loss": aligned["realized_loss"],
            "hybrid_weight_topology": weight_topology,
            "topology_variant_id": aligned["variant_id_topo"],
            "fhs_variant_id": aligned["variant_id_fhs"],
        }
    )
    out["var_exceedance_99"] = (out["realized_loss"] > out["VaR_99"]).astype(float)
    out["es_exceedance_975"] = (out["realized_loss"] > out["ES_975"]).astype(float)
    out["fz_style_score"] = _fz_style_score(
        out["realized_loss"].to_numpy(dtype=float),
        out["VaR_99"].to_numpy(dtype=float),
        out["ES_975"].to_numpy(dtype=float),
    )
    return out


def _selection_score(
    objective: str,
    *,
    mean_fz: float,
    exceedance_99: float,
    target_exceedance: float,
    coverage_weight: float,
) -> float:
    coverage_gap = abs(exceedance_99 - target_exceedance)
    if objective == "fz":
        return mean_fz
    if objective == "coverage_then_fz":
        # Lexicographic proxy: coverage gap dominates, FZ breaks ties.
        return coverage_gap * 1_000.0 + mean_fz
    if objective == "weighted_combo":
        return coverage_weight * coverage_gap + (1.0 - coverage_weight) * mean_fz
    raise ValueError(f"Unknown objective: {objective}")


def main() -> None:
    args = parse_args()
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    if not (0.0 <= args.target_var_exceedance <= 1.0):
        raise ValueError("--target-var-exceedance must be in [0,1].")
    if not (0.0 <= args.coverage_weight <= 1.0):
        raise ValueError("--coverage-weight must be in [0,1].")

    weights = _parse_weight_grid(args.weights)
    forecasts = pd.read_csv(args.forecasts)
    forecasts["forecast_date"] = pd.to_datetime(forecasts["forecast_date"], utc=False)
    forecasts["realized_date"] = pd.to_datetime(forecasts["realized_date"], utc=False)

    topo_variant_cols = _variant_columns(
        forecasts[forecasts["method"] == args.topology_method],
        ["k", "window_length", "topology_input_mode", "feature_mode", "alpha"],
    )
    fhs_variant_cols = _variant_columns(
        forecasts[forecasts["method"] == args.fhs_method],
        ["lambda"],
    )

    topo = _select_with_variant_id(forecasts, args.topology_method, topo_variant_cols)
    topo = topo[
        [
            "forecast_date",
            "realized_date",
            "split",
            "scenario_count",
            "VaR_99",
            "ES_975",
            "realized_loss",
            "variant_id",
        ]
    ].rename(
        columns={
            "forecast_date": "forecast_date_topo",
            "split": "split_topo",
            "scenario_count": "scenario_count_topo",
            "VaR_99": "VaR_99_topo",
            "ES_975": "ES_975_topo",
            "realized_loss": "realized_loss_topo",
            "variant_id": "variant_id_topo",
        }
    )
    fhs = _select_with_variant_id(forecasts, args.fhs_method, fhs_variant_cols)
    fhs = fhs[
        [
            "forecast_date",
            "realized_date",
            "split",
            "scenario_count",
            "VaR_99",
            "ES_975",
            "realized_loss",
            "variant_id",
        ]
    ].rename(
        columns={
            "forecast_date": "forecast_date_fhs",
            "split": "split_fhs",
            "scenario_count": "scenario_count_fhs",
            "VaR_99": "VaR_99_fhs",
            "ES_975": "ES_975_fhs",
            "realized_loss": "realized_loss_fhs",
            "variant_id": "variant_id_fhs",
        }
    )

    aligned = topo.merge(
        fhs,
        on=["realized_date"],
        how="inner",
    )
    aligned = aligned[
        np.isclose(aligned["realized_loss_topo"], aligned["realized_loss_fhs"])
    ].copy()
    aligned = aligned.rename(columns={"realized_loss_topo": "realized_loss"})

    if aligned.empty:
        raise RuntimeError("No aligned topology/FHS rows after merge on realized_date.")

    aligned = aligned[
        [
            "realized_date",
            "realized_loss",
            "forecast_date_topo",
            "forecast_date_fhs",
            "split_topo",
            "split_fhs",
            "variant_id_topo",
            "variant_id_fhs",
            "scenario_count_topo",
            "scenario_count_fhs",
            "VaR_99_topo",
            "ES_975_topo",
            "VaR_99_fhs",
            "ES_975_fhs",
        ]
    ]
    aligned = aligned[aligned["split_topo"] == aligned["split_fhs"]].copy()

    validation = aligned[aligned["split_topo"] == "validation"].copy()
    test = aligned[aligned["split_topo"] == "test"].copy()
    if validation.empty or test.empty:
        raise RuntimeError("Validation/test rows missing for hybrid construction.")

    scan_rows: list[dict[str, object]] = []
    best_key: tuple[str, str, float] | None = None
    best_selection_score = float("inf")

    topo_variants = sorted(validation["variant_id_topo"].unique())
    fhs_variants = sorted(validation["variant_id_fhs"].unique())
    for topo_id in topo_variants:
        for fhs_id in fhs_variants:
            pair = validation[
                (validation["variant_id_topo"] == topo_id)
                & (validation["variant_id_fhs"] == fhs_id)
            ].copy()
            if pair.empty:
                continue
            for weight in weights:
                hybrid = _build_hybrid(pair, weight_topology=weight)
                mean_fz = float(hybrid["fz_style_score"].mean())
                ex99 = float(hybrid["var_exceedance_99"].mean())
                exes = float(hybrid["es_exceedance_975"].mean())
                selection_score = _selection_score(
                    args.selection_objective,
                    mean_fz=mean_fz,
                    exceedance_99=ex99,
                    target_exceedance=args.target_var_exceedance,
                    coverage_weight=args.coverage_weight,
                )
                scan_rows.append(
                    {
                        "topology_variant_id": topo_id,
                        "fhs_variant_id": fhs_id,
                        "hybrid_weight_topology": weight,
                        "n_validation_forecasts": int(hybrid.shape[0]),
                        "validation_fz_style_mean": mean_fz,
                        "validation_exceedance_rate_99": ex99,
                        "validation_exceedance_rate_es_975": exes,
                        "validation_coverage_gap_99": abs(ex99 - args.target_var_exceedance),
                        "validation_selection_score": selection_score,
                    }
                )
                if selection_score < best_selection_score:
                    best_selection_score = selection_score
                    best_key = (topo_id, fhs_id, weight)

    if best_key is None:
        raise RuntimeError("No valid topology/FHS pair found during validation scan.")

    scan = pd.DataFrame(scan_rows).sort_values("validation_selection_score")
    scan.to_csv(output_dir / "validation_weight_scan.csv", index=False)

    best_topo_id, best_fhs_id, best_weight = best_key
    selected_validation = validation[
        (validation["variant_id_topo"] == best_topo_id)
        & (validation["variant_id_fhs"] == best_fhs_id)
    ].copy()
    selected_test = test[
        (test["variant_id_topo"] == best_topo_id) & (test["variant_id_fhs"] == best_fhs_id)
    ].copy()
    hybrid_validation = _build_hybrid(selected_validation, weight_topology=best_weight)
    hybrid_test = _build_hybrid(selected_test, weight_topology=best_weight)
    hybrid_forecasts = pd.concat([hybrid_validation, hybrid_test], ignore_index=True).sort_values(
        "realized_date"
    )
    hybrid_forecasts.to_csv(output_dir / "hybrid_forecasts.csv", index=False)

    # Component panels for the selected pair (same dates as hybrid selection).
    topo_component = selected_validation.copy()
    topo_component = pd.concat([topo_component, selected_test], ignore_index=True)
    topo_component = pd.DataFrame(
        {
            "forecast_date": topo_component["forecast_date_topo"],
            "realized_date": topo_component["realized_date"],
            "split": topo_component["split_topo"],
            "method": "topology_component",
            "scenario_count": topo_component["scenario_count_topo"],
            "VaR_99": topo_component["VaR_99_topo"],
            "ES_975": topo_component["ES_975_topo"],
            "realized_loss": topo_component["realized_loss"],
            "var_exceedance_99": (
                topo_component["realized_loss"] > topo_component["VaR_99_topo"]
            ).astype(float),
            "es_exceedance_975": (
                topo_component["realized_loss"] > topo_component["ES_975_topo"]
            ).astype(float),
        }
    )
    topo_component["fz_style_score"] = _fz_style_score(
        topo_component["realized_loss"].to_numpy(dtype=float),
        topo_component["VaR_99"].to_numpy(dtype=float),
        topo_component["ES_975"].to_numpy(dtype=float),
    )

    fhs_component = selected_validation.copy()
    fhs_component = pd.concat([fhs_component, selected_test], ignore_index=True)
    fhs_component = pd.DataFrame(
        {
            "forecast_date": fhs_component["forecast_date_fhs"],
            "realized_date": fhs_component["realized_date"],
            "split": fhs_component["split_fhs"],
            "method": "fhs_component",
            "scenario_count": fhs_component["scenario_count_fhs"],
            "VaR_99": fhs_component["VaR_99_fhs"],
            "ES_975": fhs_component["ES_975_fhs"],
            "realized_loss": fhs_component["realized_loss"],
            "var_exceedance_99": (fhs_component["realized_loss"] > fhs_component["VaR_99_fhs"]).astype(
                float
            ),
            "es_exceedance_975": (
                fhs_component["realized_loss"] > fhs_component["ES_975_fhs"]
            ).astype(float),
        }
    )
    fhs_component["fz_style_score"] = _fz_style_score(
        fhs_component["realized_loss"].to_numpy(dtype=float),
        fhs_component["VaR_99"].to_numpy(dtype=float),
        fhs_component["ES_975"].to_numpy(dtype=float),
    )

    summary = _summarize_frame(pd.concat([hybrid_forecasts, topo_component, fhs_component]))
    summary.to_csv(output_dir / "hybrid_summary.csv", index=False)

    selected = pd.DataFrame(
        [
            {
                "selected_topology_variant_id": best_topo_id,
                "selected_fhs_variant_id": best_fhs_id,
                "selected_hybrid_weight_topology": best_weight,
                "validation_objective": args.selection_objective,
                "target_var_exceedance": args.target_var_exceedance,
                "coverage_weight": args.coverage_weight,
                "validation_selection_score": best_selection_score,
                "validation_mean_fz_style_score": float(hybrid_validation["fz_style_score"].mean()),
                "validation_exceedance_rate_99": float(hybrid_validation["var_exceedance_99"].mean()),
                "validation_exceedance_rate_es_975": float(
                    hybrid_validation["es_exceedance_975"].mean()
                ),
                "n_validation_forecasts": int(hybrid_validation.shape[0]),
                "n_test_forecasts": int(hybrid_test.shape[0]),
            }
        ]
    )
    selected.to_csv(output_dir / "selected_hybrid_config.csv", index=False)

    print(f"Hybrid outputs written to: {output_dir}")
    print(selected.to_string(index=False))
    print("\nTop validation candidates:")
    print(scan.head(10).to_string(index=False))
    print("\nTest summary:")
    print(summary[summary["split"] == "test"].to_string(index=False))


if __name__ == "__main__":
    main()
